# Site settings
title: Michael Großklaus &ndash; frontend developer
email: mail@mgrossklaus.de
description: "Michael Großklaus is a frontend developer and author of miyagi, a node based component development tool for JavaScript template engines."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mgrossklaus.de"
username: "mgrossklaus"
twitter_username: mgrossklaus
github_username: mgrsskls

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: /blog/:title
sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-postcss
