# Site settings
title: Blog about frontend development by Michael Großklaus
maintitle: blog.mgrossklaus.de
subtitle: about html, css and javascript
email: mail@mgrossklaus.de
description: "Dealing with HTML, CSS and JavaScript. More about Michael Großklaus at www.mgrossklaus.de"
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://mgrossklaus.github.io/"
username: "mgrossklaus"
twitter_username: mgrossklaus
github_username:  mgrossklaus

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
sass:
  style: :compressed
