# Site settings
title: Blog about frontend development by Michael Großklaus
maintitle: blog.mgrossklaus.de
subtitle: about html, css, javascript and frontend performance
email: mail@mgrossklaus.de
description: "Dealing with HTML, CSS, JavaScript and frontend performance. More about Michael Großklaus at www.mgrossklaus.de"
baseurl: ""
url: "http://blog.mgrossklaus.de"
username: "mgrossklaus"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

sitemap:
    exclude:
      - "/feed.xml"
      - "/css/styles.scss"