# Site settings
title: Michael Großklaus
subtitle: html / css / javascript / performance / usability
email: mail@mgrossklaus.de
description: "Dealing with html, css, javascript, usability and performance. More about Michael Großklaus at www.mgrossklaus.de"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.mgrossklaus.de"
username: "mgrossklaus"
twitter_username: mgrossklaus
github_username:  mgrsskls

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
sass:
  style: :compressed
