# Site settings
title: Michael Großklaus &ndash; Freelance frontend developer
email: mail@mgrossklaus.de
description: "Michael Großklaus is a freelance frontend developer. He writes about html, css, javascript, usability, performance and accessibility."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mgrossklaus.de"
username: "mgrossklaus"
twitter_username: mgrossklaus
github_username: mgrsskls

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: /blog/:title
sass:
  style: :compressed

plugins:
  - jekyll-sitemap
